# Alokasi memori JVM untuk Gradle Build Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Mengaktifkan Android X (Library modern pengganti Support Library)
android.useAndroidX=true

# Mengaktifkan kompilasi parallel untuk mempercepat build modul
org.gradle.parallel=true

# Mengaktifkan cache build agar build berikutnya lebih cepat
org.gradle.caching=true

# Menonaktifkan konfigurasi jetifier karena kita sudah full pakai AndroidX
android.enableJetifier=false

# Mengizinkan Kotlin menggunakan optimasi internal flag
kotlin.code.style=official
