name: Build Chmods App Core (Aplikasi Induk)

on:
  workflow_dispatch: # Baris ini yang memunculkan tombol "Run manual" di GitHub

jobs:
  build:
    name: Compile Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Compile Modul Aplikasi ke APK Debug
      run: gradle :app-core:assembleDebug --no-daemon

    - name: Upload Hasil APK Ke GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chmods-app-core-debug
        path: app-core/build/outputs/apk/debug/
